### ISSUE TITLE
Kernschmelze modifies source master

### ISSUE THREAD

**Issue by Tosche** [Mark2Mark/Kernkraft#1]
Kernschmelze adds lots of zero-value pairs to the source masters. It is a bit annoying but not too problematic. The problem is that it resets some pairs to 0. They tend to be exceptions, so it effectively deletes all of my exceptions.

**Comment by Mark2Mark** [comment]
Actually that’s a significant part of Kernschmelze. The zero values are set on purpose (and necessary in order to  be able to interpolate at all.

How it deals with your exceptions is something I need to have a look at. Can you make up an example case for me, to reproduce and test, please?

**Comment by Mark2Mark** [comment]
I checked and for me the exceptions are all fine and perfectly interpolated.
Could you please provide me with a dummy file (just some squares as glyphs) that represent the kind of kerning you start with. And then – very important – what exactly did you try? Interpolate or Copy? From which masters to which? Which Glyphs version? And so on …

Thanks!

**Comment by Tosche** [comment]
I'm so sorry Mark, I now cannot reproduce the result. Please consider it closed until I can.

**Comment by Mark2Mark** [comment]
Not a problem at all, Tosche. I’m glad to help, let me know if you encounter any problems (again).
